// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Json2CSharp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJson2CSharpPackageString = "9ce6338e-f14c-4b38-9c86-ea29abb3b1ec";
        public static Guid guidJson2CSharpPackage = new Guid(guidJson2CSharpPackageString);

        public const string guidJson2CSharpPackageCmdSetString = "917d3b37-34f4-4298-8172-d41e5adaaaeb";
        public static Guid guidJson2CSharpPackageCmdSet = new Guid(guidJson2CSharpPackageCmdSetString);

        public const string guidImagesString = "1ee48d50-9a2c-426d-8d6c-1841d996f397";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ConvertJson2CSharpCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}